language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - yes | sdkmanager 'platforms;android-27'

before_script:
  - cp signing.properties.travis signing.properties

after_failure:
  - cat app/build/outputs/lint-results-*.html
