language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.1
    - android-24
    - extra-android-m2repository

before_script:
  - cp signing.properties.travis signing.properties

after_failure:
  - cat app/build/outputs/lint-results-*.html
